# Generated by Django 3.1.7 on 2021-02-24 13:16

from django.db import migrations


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gm_dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FnaSheet',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('gm_dashboard.sheet',),
        ),
    ]
