# Generated by Django 3.1.7 on 2021-02-24 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sheet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('display_name', models.TextField()),
                ('config_name', models.TextField()),
                ('csv_path', models.TextField()),
                ('script_path', models.TextField()),
                ('code', models.TextField()),
                ('sheet_type', models.CharField(choices=[('FnA', 'FnA'), ('GM', 'GM')], max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='GMSheet',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('gm_dashboard.sheet',),
        ),
    ]
